# vim ft=yaml
# travis-ci.org and coveralls definition for PsychoPy tests
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install lsb-release
  - source /etc/lsb-release
  - echo ${DISTRIB_CODENAME}
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -
  - travis_retry sudo apt-get update -qq
  - sudo apt-cache policy           # What is actually available?
  - travis_retry sudo apt-get install -qq xvfb xauth libgl1-mesa-dri
  - travis_retry sudo apt-get install -qq python-pygame python-opengl
  - travis_retry sudo -H pip install --upgrade -qq pip
  - travis_retry sudo -H pip install --upgrade -qq soundfile
  - travis_retry sudo -H pip install --upgrade -qq sounddevice
# pyglet 1.2.2
  - travis_retry sudo -H pip install -qq pyglet
  - python -c 'import pyglet; print pyglet.version'
  - travis_retry sudo -H pip install -q pillow
  - travis_retry sudo -H pip install -q pyosf
  - travis_retry sudo -H pip install -q xlrd
#  - python -c 'import Image; print Image.PILLOW_VERSION'
  - travis_retry sudo -H pip install -qq gevent # Don't use apt-get (too old version of gevent)
  - travis_retry sudo apt-get install -qq python-yaml python-xlib
  - travis_retry sudo -H pip install -qq psutil # Don't use apt-get (too old version of psutil)
  - travis_retry sudo -H pip install -qq msgpack-python #not apt-get (no permissions for universe)
  - travis_retry sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-lxml
  - travis_retry sudo apt-get install -qq python-configobj python-imaging python-openpyxl python-mock python-wxgtk2.8 libavbin0 python-pyo
  - travis_retry sudo apt-get install -qq python-pandas
  - travis_retry sudo apt-get install -qq python-qt4
  - travis_retry sudo pip install -qq codecov
install:
  - travis_retry sudo apt-get install -qq flac
  - flac -version
  #- travis_retry sudo apt-get install -qq language-pack-en-base  # English locales
  - travis_retry sudo apt-get install -qq language-pack-ja-base  # Japanese locale
  #- sudo dpkg-reconfigure locales
  #- locale -a       # list available locales
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -q coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -q pyserial pycrsltd; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then xvfb-run -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" coverage run --rcfile=.travis_coveragerc psychopy/tests/runPytest.py -v -s -m "not needs_sound"; else { echo "TODO while avoiding duplication"; exit 1; } fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
  - codecov
